### ISSUE TITLE
AttributeError for remote schema with input type

### ISSUE THREAD

**Issue by erilea123** [mirumee/ariadne-codegen#192]
Hi, I tried to use code from main branch for unreleased pydantic v2 support but I encountered some issues. I'm not sure if you are already aware of them, but I didn't find any mentions of them in other issues.

I get AttributeError for remote schema with any input type, I created small example to demonstrate that.
Server code:
```py
from ariadne import QueryType, make_executable_schema
from ariadne.asgi import GraphQL

type_defs = """
    type Query {
        hello(input: Input): String!
    }
    
    input Input {
        inputValue: Int!
    }
"""

query = QueryType()


@query.field("hello")
def resolve_hello(_, info, input):
    value = input.get("value")
    return f"Hello! The provided value is {value}"


schema = make_executable_schema(type_defs, query)

app = GraphQL(schema, debug=True)
```

Query:
```gql
query testQuery($input: Input) {
  hello(input: $input)
}

```

Anonimized error:
```bash
❯ ariadne-codegen
Selected strategy: client
Using schema from 'http://0.0.0.0:8000'.
Reading queries from 'queries.graphql'.
Using 'graphql_client' as package name.
Generating package into '...'.
Using 'Client' as client name.
Using 'AsyncBaseClient' as base client class.
Coping base client class from '.../client_generators/dependencies/async_base_client.py'.
Generating enums into 'enums.py'.
Generating inputs into 'input_types.py'.
Generating fragments into 'fragments.py'.
Not including comments.
Converting fields and arguments name to snake case.
Generating async client.
No files to copy.
No plugin is being used.
Traceback (most recent call last):
  File ".../bin/ariadne-codegen", line 8, in <module>
    sys.exit(main())
  File ".../lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File ".../lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File ".../lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".../lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File ".../ariadne_codegen/main.py", line 34, in main
    client(config_dict)
  File ".../ariadne_codegen/main.py", line 69, in client
    package_generator = PackageGenerator(
  File ".../ariadne_codegen/client_generators/package.py", line 146, in __init__
    else InputTypesGenerator(
  File ".../ariadne_codegen/client_generators/input_types.py", line 69, in __init__
    self._class_defs: List[ast.ClassDef] = [
  File ".../ariadne_codegen/client_generators/input_types.py", line 70, in <listcomp>
    self._parse_input_definition(d) for d in self._filter_input_types()
  File ".../ariadne_codegen/client_generators/input_types.py", line 137, in _parse_input_definition
    value=parse_input_field_default_value(
  File ".../ariadne_codegen/client_generators/input_fields.py", line 103, in parse_input_field_default_value
    if not default_value and not isinstance(node.type, NonNullTypeNode):
AttributeError: 'NoneType' object has no attribute 'type'
```

The same works fine on 0.7.1, but of course without the v2. I'm not sure what's the process for issues related to not released things, so feel free to close it if it's not relevant. btw Are there plans to release these features?
